### ISSUE TITLE
Skills for Highelves

### ISSUE THREAD

**Issue by Enigma0216** [BSData/blood-bowl-2016#2]
High Elves can't chose General skills when leveling up, but have access to two sets of agility skills. One of them should be replaced with the General skills
![High elves](https://user-images.githubusercontent.com/83012730/115710175-59048600-a372-11eb-8e10-1d271999f5d9.jpg)
Could someone fix this? (I'd rather not play the 2020 ed.)
Thanks!

**Comment by Enigma0216** [comment]
Issue marked as closed, but the issue remains. Still can't add general skills to High Elves on star player rolls.

**Comment by shaner11** [comment]
> Issue marked as closed, but the issue remains. Still can't add general skills to High Elves on star player rolls.

This one is a stupid mistake on my end. The issue has been resolved, but I made the horrible mistake of renaming the game system file. As it turns out this stops updates from working properly. Try removing and re-downloading the data files. That should resolve the issue moving forwards.

**Comment by Enigma0216** [comment]
Thanks for fixing it! But I notice that Throwers still can't chose general skills, but have two choices of Agility instead, as before :/
Would be great if you could take a look!
Thanks in advance!

**Comment by shaner11** [comment]
![image](https://user-images.githubusercontent.com/73592713/128822861-d928668a-6b98-4203-9867-547c84f2f8cb.png)
I've just triple checked and this is what comes up on my end. My copy of the data is identical to the current release, so the issue is likely on your end.

As mentioned previously I was able to reproduce your issue on another device with a copy of the pervious update, and it is caused by that update not preforming correctly. It can be solved by deleting the catalogue and downloading a fresh copy of it. This will not remove any teams you have created using it, and they should load up with the proper fixes after this is done.

**Comment by Enigma0216** [comment]
Hi again!
I just refreshed everything, and guess what?
Everything works as it should!
Once again, thanks a lot!!

________________________________
Från: crazydude11 ***@***.***>
Skickat: den 10 augusti 2021 09:07
Till: BSData/blood-bowl-2016 ***@***.***>
Kopia: Enigma0216 ***@***.***>; Author ***@***.***>
Ämne: Re: [BSData/blood-bowl-2016] Skills for Highelves (#2)


[image]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F73592713%2F128822861-d928668a-6b98-4203-9867-547c84f2f8cb.png&data=04%7C01%7C%7C426c8cf8da3f4d637a3a08d95bcd8776%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637641760556283843%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=deGhg45cTnqODWqB4ZfM8c5hGVcn7top3lGSJPBRl4U%3D&reserved=0>
I've just triple checked and this is what comes up on my end. My copy of the data is identical to the current release, so the issue is likely on your end.

As mentioned previously I was able to reproduce your issue on another device with a copy of the pervious update, and it is caused by that update not preforming correctly. It can be solved by deleting the catalogue and downloading a fresh copy of it. This will not remove any teams you have created using it, and they should load up with the proper fixes after this is done.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBSData%2Fblood-bowl-2016%2Fissues%2F2%23issuecomment-895784227&data=04%7C01%7C%7C426c8cf8da3f4d637a3a08d95bcd8776%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637641760556293793%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tAFdBU2MXtgyCbT%2FGTWZEBP4x9yq73cUSZ1CLNErVWQ%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATZKY6WV2TSXNVKTVV7TCN3T4DF3LANCNFSM5AQRAZRQ&data=04%7C01%7C%7C426c8cf8da3f4d637a3a08d95bcd8776%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637641760556293793%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UhD1CHks6QThG2r3ZxGBTyS6bjDrqwjwqCrk48gsL30%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C426c8cf8da3f4d637a3a08d95bcd8776%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637641760556303755%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0xJYL6EaTq0QErnDrATEZDOR3jhbQ7CTsOzdLllH9VE%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7C%7C426c8cf8da3f4d637a3a08d95bcd8776%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637641760556303755%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nBhGIYau4TkCSLtew%2F1fYhmH5pOc9unpMsrbAQdm%2Be8%3D&reserved=0>.
